[package]
name = "lockfile-guard"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.10"
walkdir = "2.4"
colored = "2.1"
ignore = "0.4"

[lints.clippy]
pedantic = "warn"
# ==== Security-related clippy lints
arithmetic_side_effects = "warn"
as_conversions = "warn"
